name: Publish Image
on:
  release:
    types: [created]

jobs:
  publish-image:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Gather image info
        id: info
        run: |
          echo "::set-output name=repo-owner::${GITHUB_REPOSITORY_OWNER,,}"

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Image Metadata
        id: base-meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ steps.info.outputs.repo-owner }}/acapy-plugin-pickup
          tags: |
            type=semver
            type=sha

      - name: Build and Push Image to ghcr.io
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: docker/Dockerfile.release
          tags: ${{ steps.base-meta.outputs.tags }}
          labels: ${{ steps.base-meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
